# Generated by Django 4.2.20 on 2025-05-21 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, max_length=10)),
                ('tags', models.CharField(choices=[('Array', 'Array'), ('STRING', 'String'), ('DSA', 'Dsa')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_example', models.TextField()),
                ('output_example', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='problems.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='problems_qu_difficu_02b6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='problems_qu_created_5f6980_idx'),
        ),
        migrations.AddIndex(
            model_name='example',
            index=models.Index(fields=['question', 'order'], name='problems_ex_questio_dee63e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='example',
            unique_together={('question', 'order')},
        ),
    ]
