# Generated by Django 4.2 on 2025-07-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
    ]
