# Generated by Django 4.2.20 on 2025-05-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
    ]
