# Generated by Django 4.2.20 on 2025-05-24 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_testcase_solvedcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
