# Generated by Django 4.2.20 on 2025-06-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.CharField(choices=[('ARRAY', 'Array'), ('STRING', 'String'), ('DSA', 'Dsa')]),
        ),
    ]
