# Generated by Django 4.2.20 on 2025-06-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_question_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='example',
            name='problems_ex_questio_dee63e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='example',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='example',
            name='order',
        ),
    ]
