# Generated by Django 4.2.20 on 2025-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_example_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_contributed',
            field=models.BooleanField(default=False),
        ),
    ]
