# Generated by Django 4.2.20 on 2025-06-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_question_is_contributed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='order',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
