# Generated by Django 4.2.20 on 2025-06-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_alter_testcase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contribution_status',
            field=models.CharField(blank=True, choices=[('QUESTION_SUBMITTED', 'Question Submitted'), ('TEST_CASES_SUBMITTED', 'Test Cases Submitted'), ('CODE_SUBMITTED', 'Code Submitted'), ('COMPLETED', 'Completed')], default='QUESTION_SUBMITTED', max_length=20),
        ),
    ]
