# Generated by Django 4.2 on 2025-08-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipant',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('joined', 'Joined'), ('left', 'Left'), ('kicked', 'Kicked'), ('battle', 'Battle')], default='waiting', max_length=20),
        ),
    ]
