# Generated by Django 4.2.20 on 2025-05-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
