# Generated by Django 4.2.20 on 2025-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomparticipant',
            options={'ordering': ['joined_at']},
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('joined', 'Joined'), ('left', 'Left'), ('kicked', 'Kicked')], default='waiting', max_length=20),
        ),
        migrations.AddIndex(
            model_name='roomparticipant',
            index=models.Index(fields=['room', 'user'], name='room_roompa_room_id_b398de_idx'),
        ),
    ]
