# Generated by Django 4.2.20 on 2025-05-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_roomparticipant_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_ranked',
            field=models.BooleanField(default=True),
        ),
    ]
