# Generated by Django 4.2.20 on 2025-04-22 09:24

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_roomparticipant_options_roomparticipant_ready_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AddField(
            model_name='room',
            name='join_code',
            field=models.CharField(max_length=6, unique=True, null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='room',
            name='participant_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['join_code'], name='room_room_join_co_a606a6_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['owner'], name='room_room_owner_i_d2ecca_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['visibility'], name='room_room_visibil_e77d70_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='room_room_status_6f53d2_idx'),
        ),
        migrations.AddIndex(
            model_name='roomparticipant',
            index=models.Index(fields=['status'], name='room_roompa_status_fd4d3c_idx'),
        ),
    ]