# Generated by Django 4.2.20 on 2025-04-22 09:32

from django.db import migrations, models
from room.models import generate_join_code

class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_add_join_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Room',
            name='join_code',
            field=models.CharField(default=generate_join_code, editable=False, max_length=6, unique=True),
        ),
    ]