# Generated by Django 4.2.20 on 2025-06-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_alter_question_contribution_status'),
        ('room', '0005_chatmessage_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.question'),
        ),
    ]
