# Generated by Django 4.2.20 on 2025-04-23 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_join_code'),
        ('room', '0005_add_join_codes'),
    ]

    operations = [
    ]
