# Generated by Django 4.2.20 on 2025-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_room_active_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Time when the battle started', null=True),
        ),
    ]
