# Generated by Django 4.2 on 2025-07-20 09:55

import authentication.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('profile_picture', models.URLField(blank=True, default=authentication.models.CustomUser.get_default_profile_picture, max_length=500, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_type', models.CharField(choices=[('manual', 'Manual'), ('google', 'Google'), ('github', 'GitHub')], default='manual', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('total_battles', models.IntegerField(default=0, null=True)),
                ('battles_won', models.IntegerField(default=0)),
                ('total_contributions', models.IntegerField(default=0)),
                ('last_win', models.DateField(blank=True, null=True)),
                ('battle_streak', models.IntegerField(default=0)),
                ('accepted_contributions', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_encrypted', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_type', models.CharField(choices=[('registration', 'Registration'), ('forgot_password', 'Forgot Password')], default='registration', max_length=20)),
            ],
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email'], name='authenticat_email_8d7fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_98a691_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['is_verified'], name='authenticat_is_veri_755692_idx'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email', 'username'], name='authenticat_email_ef9292_idx'),
        ),
    ]
