# Generated by Django 4.2.20 on 2025-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['is_verified'], name='authenticat_is_veri_755692_idx'),
        ),
    ]
