# Generated by Django 4.2.20 on 2025-04-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_otp_is_verified_otp_authenticat_is_veri_755692_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
