# Generated by Django 4.2.20 on 2025-04-07 09:18

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=authentication.models.CustomUser.get_default_profile_picture, null=True, upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
