# Generated by Django 4.2.20 on 2025-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_contributions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='battles_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_battles',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_contributions',
            field=models.IntegerField(default=0),
        ),
    ]
