# Generated by Django 4.2.20 on 2025-06-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_otp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('forgot_password', 'Forgot Password')], default='registration', max_length=20),
        ),
    ]
