# Generated by Django 4.2.20 on 2025-06-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_otp_otp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='battle_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_win',
            field=models.DateField(blank=True, null=True),
        ),
    ]
