# Generated by Django 4.2.20 on 2025-06-29 09:40

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_battle_streak_customuser_last_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, default=authentication.models.CustomUser.get_default_profile_picture, max_length=500, null=True),
        ),
    ]
