# Generated by Django 4.2.20 on 2025-06-26 05:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0012_alter_question_contribution_status'),
        ('room', '0006_room_active_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_results', to='problems.question')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='room.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['battle_id'], name='battle_batt_battle__6bbc17_idx'), models.Index(fields=['created_at'], name='battle_batt_created_e38fc7_idx')],
            },
        ),
    ]
