# Generated by Django 4.2 on 2025-07-20 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_results', to='problems.question')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='room.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userranking',
            index=models.Index(fields=['user'], name='battle_user_user_id_4ca911_idx'),
        ),
        migrations.AddIndex(
            model_name='userranking',
            index=models.Index(fields=['points'], name='battle_user_points_a7479c_idx'),
        ),
        migrations.AddIndex(
            model_name='battleresult',
            index=models.Index(fields=['battle_id'], name='battle_batt_battle__6bbc17_idx'),
        ),
        migrations.AddIndex(
            model_name='battleresult',
            index=models.Index(fields=['created_at'], name='battle_batt_created_e38fc7_idx'),
        ),
    ]
