# Generated by Django 4.2 on 2025-08-13 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_rankings', to=settings.AUTH_USER_MODEL),
        ),
    ]
